export { default as Earth } from './earth.png'
export { default as Jupiter } from './jupiter.png'
export { default as Mars } from './mars.png'
export { default as Mercury } from './mercury.png'
export { default as Neptune } from './neptune.png'
export { default as Saturn } from './saturn.png'
export { default as Uranus } from './uranus.png'
export { default as Venus } from './venus.png'
